export const products = [
  // ─── INSTRUMENTE ────────────────────────────────
  { slug: "chiureta-dubla-dietter-baumann", name: "Chiuretă dublă Dietter Baumann", description: "Este un instrument dublu, format din 2 capete. Chiuretă dublă profesională Dietter Baumann, ideală pentru îndepărtarea cuticulelor și curățarea matricei unghiale. Oțel inoxidabil chirurgical de calitate superioară germană.", price: 4500, category: "instrumente", subcategory: "instrumente-manichiura", inStock: true, featured: false, imageUrl: "https://emmanails.ro/wp-content/uploads/2025/05/DSC_8288.jpg", images: ["https://emmanails.ro/wp-content/uploads/2025/05/DSC_8288.jpg", "https://emmanails.ro/wp-content/uploads/2025/05/DSC_8289.jpg"] },
  { slug: "cleste-profesional-dietter-baumann", name: "Clește profesional Dietter Baumann", description: "Clește profesional Dietter Baumann pentru cuticulele. Lame ascuțite din oțel chirurgical german, mâner ergonomic.", price: 16000, category: "instrumente", subcategory: "instrumente-manichiura", inStock: true, featured: true, imageUrl: "https://emmanails.ro/wp-content/uploads/2025/05/DSC_8271.jpg", images: ["https://emmanails.ro/wp-content/uploads/2025/05/DSC_8271.jpg", "https://emmanails.ro/wp-content/uploads/2025/05/DSC_8272.jpg", "https://emmanails.ro/wp-content/uploads/2025/05/WhatsApp-Image-2024-08-22-at-08.09.53-1.jpeg"] },
  { slug: "foarfece-exclusive-staleks", name: "Foarfece Exclusive Staleks", description: "Foarfece pentru cuticulă, taie cu precizie. Lamele sunt ascuțite și subțiri, ușor curbată.", price: 13500, category: "instrumente", subcategory: "instrumente-manichiura", inStock: true, featured: false, imageUrl: "https://emmanails.ro/wp-content/uploads/2025/05/DSC_8278.jpg", images: ["https://emmanails.ro/wp-content/uploads/2025/05/DSC_8278.jpg", "https://emmanails.ro/wp-content/uploads/2025/05/DSC_8279.jpg", "https://emmanails.ro/wp-content/uploads/2025/05/forbice-per-cuticole-staleks-exclusive-sx-221-magnolia-21mm.png"] },
  { slug: "foarfece-maniprof-110mm", name: "Foarfece Maniprof 110mm", description: "Foarfece pentru cuticulă, taie cu precizie. Lamele sunt drepte, ascuțite și subțiri. 110mm.", price: 13000, category: "instrumente", subcategory: "instrumente-manichiura", inStock: true, featured: false, imageUrl: "https://emmanails.ro/wp-content/uploads/2025/05/DSC_8273.jpg", images: ["https://emmanails.ro/wp-content/uploads/2025/05/DSC_8273.jpg", "https://emmanails.ro/wp-content/uploads/2025/05/DSC_8274.jpg"] },
  { slug: "foarfece-maniprof-97mm", name: "Foarfece Maniprof 97mm", description: "Foarfece pentru cuticulă, taie cu precizie. Lamele sunt drepte, ascuțite și subțiri. 97mm.", price: 13500, category: "instrumente", subcategory: "instrumente-manichiura", inStock: true, featured: false, imageUrl: "https://emmanails.ro/wp-content/uploads/2025/05/DSC_8275.jpg", images: ["https://emmanails.ro/wp-content/uploads/2025/05/DSC_8275.jpg", "https://emmanails.ro/wp-content/uploads/2025/05/DSC_8277.jpg"] },
  { slug: "instrument-profesional-dietter-baumann-pentru-unghii-incarnate-si-bataturi", name: "Instrument profesional Dietter Baumann pentru unghii încarnate și bătături", description: "Instrument profesional dublu, special conceput pentru tratamentul unghiilor încarnate și bătăturilor. Oțel chirurgical german.", price: 13900, category: "instrumente", subcategory: "instrumente-pedichiura", inStock: true, featured: true, imageUrl: "https://emmanails.ro/wp-content/uploads/2025/05/DSC_8269.jpg", images: ["https://emmanails.ro/wp-content/uploads/2025/05/DSC_8269.jpg", "https://emmanails.ro/wp-content/uploads/2025/05/DSC_8267.jpg"] },
  { slug: "microforfecuta-tweezer-staleks-pro-expert", name: "Microforfecuță — Tweezer Staleks Pro Expert", description: "Instrument pentru manichiură și pedichiură. Lamele sunt ascuțite și subțiri, ușor curbată.", price: 9900, category: "instrumente", subcategory: "instrumente-manichiura", inStock: true, featured: false, imageUrl: "https://emmanails.ro/wp-content/uploads/2025/05/DSC_8280.jpg", images: ["https://emmanails.ro/wp-content/uploads/2025/05/DSC_8280.jpg", "https://emmanails.ro/wp-content/uploads/2025/05/DSC_8282.jpg", "https://emmanails.ro/wp-content/uploads/2025/05/Tijera-para-manicure-Staleks-Expert-90-1-Enails-1-1024x1024-1.jpg"] },
  { slug: "oferta-cleste-foarfece-chiureta", name: "Ofertă clește + foarfece + chiuretă", description: "Set complet la preț special: clește + foarfece + chiuretă.", price: 34500, salePrice: 29500, category: "instrumente", subcategory: "instrumente-set", inStock: true, featured: true, imageUrl: "https://emmanails.ro/wp-content/uploads/2025/06/DSC_8291.jpg", images: ["https://emmanails.ro/wp-content/uploads/2025/06/DSC_8291.jpg", "https://emmanails.ro/wp-content/uploads/2025/06/DSC_8293.jpg"] },
  { slug: "penseta-pedichiura-staleks-pro-podo", name: "Pensetă pedichiură Staleks Pro Podo", description: "Pentru îndepărtarea elementelor unghiilor încarnate din pliurile laterale și bătăturilor subunghiale.", price: 6500, category: "instrumente", subcategory: "instrumente-pedichiura", inStock: true, featured: false, imageUrl: "https://emmanails.ro/wp-content/uploads/2025/05/DSC_8284.jpg", images: ["https://emmanails.ro/wp-content/uploads/2025/05/DSC_8284.jpg", "https://emmanails.ro/wp-content/uploads/2025/05/DSC_8285.jpg"] },

  // ─── POLYGEL ──────────────────────────────────────
  { slug: "polygel-emma-nails", name: "Polygel Emma Nails", description: "Cel mai top produs ever! Cu formulă revoluționară, foarte rezistent și ideal pentru construcția unghiilor pe tips/șablon/la întreținere cu schimbarea arhitecturii/french interior.", price: 8000, category: "polygel", subcategory: "polygel-clasic", size: "30g", inStock: true, featured: true, imageUrl: "https://emmanails.ro/wp-content/uploads/2025/04/29.jpg", images: ["https://emmanails.ro/wp-content/uploads/2025/04/29.jpg"] },
  { slug: "polygel-verde", name: "Polygel Verde", description: "PolyGel verde — culoare vibrantă. Cu formulă revoluționară.", price: 3100, category: "polygel", subcategory: "polygel-color", size: "30g", inStock: true, featured: false, imageUrl: "https://emmanails.ro/wp-content/uploads/2025/04/29.jpg", images: ["https://emmanails.ro/wp-content/uploads/2025/04/29.jpg"] },
  { slug: "polygel-emma-nails-color-01-60g", name: "Polygel Emma Nails Color 01, 60g", description: "Cu o formulă revoluționară, foarte rezistent. Format economic 60g.", price: 14000, category: "polygel", subcategory: "polygel-color", size: "60g", inStock: true, featured: true, imageUrl: "https://emmanails.ro/wp-content/uploads/2025/05/1.jpg", images: ["https://emmanails.ro/wp-content/uploads/2025/05/1.jpg"] },
  { slug: "polygel-emma-nails-color-06-30g", name: "Polygel Emma Nails Color 06, 30g", description: "Cu o formulă revoluționară, foarte rezistent.", price: 8000, category: "polygel", subcategory: "polygel-color", size: "30g", inStock: true, featured: false, imageUrl: "https://emmanails.ro/wp-content/uploads/2025/05/06.jpg", images: ["https://emmanails.ro/wp-content/uploads/2025/05/06.jpg"] },
  { slug: "polygel-emma-nails-color-08-30g", name: "Polygel Emma Nails Color 08, 30g", description: "Cu o formulă revoluționară, foarte rezistent.", price: 8000, category: "polygel", subcategory: "polygel-color", size: "30g", inStock: true, featured: false, imageUrl: "https://emmanails.ro/wp-content/uploads/2025/05/08.jpg", images: ["https://emmanails.ro/wp-content/uploads/2025/05/08.jpg"] },
  { slug: "polygel-emma-nails-color-26-30g", name: "Polygel Emma Nails Color 26, 30g", description: "Cu o formulă revoluționară, foarte rezistent.", price: 8000, category: "polygel", subcategory: "polygel-color", size: "30g", inStock: true, featured: false, imageUrl: "https://emmanails.ro/wp-content/uploads/2025/05/26.jpg", images: ["https://emmanails.ro/wp-content/uploads/2025/05/26.jpg"] },
  { slug: "polygel-emma-nails-color-27-60g", name: "Polygel Emma Nails Color 27, 60g", description: "Cu o formulă revoluționară. Format economic 60g.", price: 14000, category: "polygel", subcategory: "polygel-color", size: "60g", inStock: true, featured: false, imageUrl: "https://emmanails.ro/wp-content/uploads/2025/05/27.jpg", images: ["https://emmanails.ro/wp-content/uploads/2025/05/27.jpg"] },
  { slug: "polygel-emma-nails-color-29-30g", name: "Polygel Emma Nails Color 29, 30g", description: "Cu o formulă revoluționară, foarte rezistent.", price: 8000, category: "polygel", subcategory: "polygel-color", size: "30g", inStock: true, featured: false, imageUrl: "https://emmanails.ro/wp-content/uploads/2025/05/29.jpg", images: ["https://emmanails.ro/wp-content/uploads/2025/05/29.jpg"] },
  { slug: "polygel-emma-nails-color-30-30g", name: "Polygel Emma Nails Color 30, 30g", description: "Cu o formulă revoluționară, foarte rezistent.", price: 8000, category: "polygel", subcategory: "polygel-color", size: "30g", inStock: true, featured: false, imageUrl: "https://emmanails.ro/wp-content/uploads/2025/05/30.jpg", images: ["https://emmanails.ro/wp-content/uploads/2025/05/30.jpg"] },
  { slug: "polygel-emma-nails-color-32-30g", name: "Polygel Emma Nails Color 32, 30g", description: "Cu o formulă revoluționară, foarte rezistent.", price: 8000, category: "polygel", subcategory: "polygel-color", size: "30g", inStock: true, featured: false, imageUrl: "https://emmanails.ro/wp-content/uploads/2025/05/32.jpg", images: ["https://emmanails.ro/wp-content/uploads/2025/05/32.jpg"] },
  { slug: "polygel-emma-nails-color-34-30g", name: "Polygel Emma Nails Color 34, 30g", description: "Cu o formulă revoluționară, foarte rezistent.", price: 8000, category: "polygel", subcategory: "polygel-color", size: "30g", inStock: true, featured: false, imageUrl: "https://emmanails.ro/wp-content/uploads/2025/05/34.jpg", images: ["https://emmanails.ro/wp-content/uploads/2025/05/34.jpg"] },
  { slug: "polygel-emma-nails-color-44-30g", name: "Polygel Emma Nails Color 44, 30g", description: "Cu o formulă revoluționară, foarte rezistent.", price: 8000, category: "polygel", subcategory: "polygel-color", size: "30g", inStock: true, featured: false, imageUrl: "https://emmanails.ro/wp-content/uploads/2025/05/44.jpg", images: ["https://emmanails.ro/wp-content/uploads/2025/05/44.jpg"] },
  { slug: "polygel-emma-nails-color-45-30g", name: "Polygel Emma Nails Color 45, 30g", description: "Cu o formulă revoluționară, foarte rezistent.", price: 8000, category: "polygel", subcategory: "polygel-color", size: "30g", inStock: true, featured: false, imageUrl: "https://emmanails.ro/wp-content/uploads/2025/05/45.jpg", images: ["https://emmanails.ro/wp-content/uploads/2025/05/45.jpg"] },
  { slug: "polygel-emma-nails-color-kd2-30g", name: "Polygel Emma Nails Color KD2, 30g", description: "Din colecția specială KD. Cu formulă revoluționară.", price: 8000, category: "polygel", subcategory: "polygel-color", size: "30g", inStock: true, featured: false, imageUrl: "https://emmanails.ro/wp-content/uploads/2025/05/KD2.jpg", images: ["https://emmanails.ro/wp-content/uploads/2025/05/KD2.jpg"] },
  { slug: "polygel-emma-nails-color-kd3-30g", name: "Polygel Emma Nails Color KD3, 30g", description: "Din colecția specială KD. Cu formulă revoluționară.", price: 8000, category: "polygel", subcategory: "polygel-color", size: "30g", inStock: true, featured: false, imageUrl: "https://emmanails.ro/wp-content/uploads/2025/05/KD3.jpg", images: ["https://emmanails.ro/wp-content/uploads/2025/05/KD3.jpg"] },
  { slug: "reflective-polygel-emma-nails-color-09-30g", name: "Reflective Polygel Emma Nails Color 09, 30g", description: "PolyGel reflectiv cu efect strălucitor spectaculos.", price: 8000, category: "polygel", subcategory: "polygel-reflective", size: "30g", inStock: true, featured: true, imageUrl: "https://emmanails.ro/wp-content/uploads/2025/05/09.jpg", images: ["https://emmanails.ro/wp-content/uploads/2025/05/09.jpg"] },
  { slug: "reflective-polygel-emma-nails-color-19-30g", name: "Reflective Polygel Emma Nails Color 19, 30g", description: "PolyGel reflectiv cu efect strălucitor unic.", price: 8000, category: "polygel", subcategory: "polygel-reflective", size: "30g", inStock: true, featured: false, imageUrl: "https://emmanails.ro/wp-content/uploads/2025/05/19.jpg", images: ["https://emmanails.ro/wp-content/uploads/2025/05/19.jpg"] },
  { slug: "reflective-polygel-emma-nails-color-24-30g", name: "Reflective Polygel Emma Nails Color 24, 30g", description: "PolyGel reflectiv cu efect holografic.", price: 8000, category: "polygel", subcategory: "polygel-reflective", size: "30g", inStock: true, featured: false, imageUrl: "https://emmanails.ro/wp-content/uploads/2025/05/25.jpg", images: ["https://emmanails.ro/wp-content/uploads/2025/05/25.jpg"] },
  { slug: "reflective-polygel-emma-nails-color-25-30g", name: "Reflective Polygel Emma Nails Color 25, 30g", description: "PolyGel reflectiv cu efect fascinant.", price: 8000, category: "polygel", subcategory: "polygel-reflective", size: "30g", inStock: true, featured: false, imageUrl: "https://emmanails.ro/wp-content/uploads/2025/05/25.jpg", images: ["https://emmanails.ro/wp-content/uploads/2025/05/25.jpg"] },

  // ─── ACRYLIC LIQUID ─────────────────────────────────
  { slug: "acrylic-liquid-soft-nude", name: "Acrylic Extension Liquid — Soft Nude, 30g", description: "Acrylic Liquid Emma Nails — material de înaltă performanță pentru tehnicienii care solicită durabilitate extremă. Formula avansată permite o modelare fluidă, transformând amestecul de pudră acrilică într-o masă omogenă, ușor de sculptat. Timp de lucru optimizat, aderență chimică superioară, rezistență UV și anti-îngălbenire. Nuanța Soft Nude — camuflaj natural perfect.", price: 9500, category: "acrylic-liquid", subcategory: "acrylic-liquid", size: "30g", inStock: true, featured: true, colorHex: "#DCBFA8", imageUrl: "/acrylic-soft-nude.jpg", images: ["/acrylic-soft-nude.jpg"] },
  { slug: "acrylic-liquid-soft-lilac", name: "Acrylic Extension Liquid — Soft Lilac, 30g", description: "Acrylic Liquid Emma Nails — material de înaltă performanță cu formulă avansată ce permite o modelare fluidă și control absolut. Aderență chimică superioară, rezistență UV și structură de densitate înaltă. Nuanța Soft Lilac — eleganță discretă cu reflexe liliac.", price: 9500, category: "acrylic-liquid", subcategory: "acrylic-liquid", size: "30g", inStock: true, featured: false, colorHex: "#C4A0BE", imageUrl: "/acrylic-soft-lilac.jpg", images: ["/acrylic-soft-lilac.jpg"] },
  { slug: "acrylic-liquid-pink-luna", name: "Acrylic Extension Liquid — Pink Luna, 30g", description: "Acrylic Liquid Emma Nails — material de înaltă performanță cu formulă avansată. Control absolut al materialului, finit de precizie și versatilitate structurală. Ideal pentru extensii pe șablon, protecția unghiei naturale sau utilizare în tips. Nuanța Pink Luna — roz delicat și feminin.", price: 9500, category: "acrylic-liquid", subcategory: "acrylic-liquid", size: "30g", inStock: true, featured: false, colorHex: "#E8A0B0", imageUrl: "/acrylic-pink-luna.jpg", images: ["/acrylic-pink-luna.jpg"] },
  { slug: "acrylic-liquid-mood-nude", name: "Acrylic Extension Liquid — Mood Nude, 30g", description: "Acrylic Liquid Emma Nails — material de înaltă performanță. Timp de lucru optimizat, aderență chimică superioară și rezistență UV anti-îngălbenire. Manichiură robustă, subțire și cu o duritate remarcabilă. Nuanța Mood Nude — nude cald și sofisticat.", price: 9500, category: "acrylic-liquid", subcategory: "acrylic-liquid", size: "30g", inStock: true, featured: false, colorHex: "#D4AA90", imageUrl: "/acrylic-mood-nude.jpg", images: ["/acrylic-mood-nude.jpg"] },
  { slug: "acrylic-liquid-ivory-silk", name: "Acrylic Extension Liquid — Ivory Silk, 30g", description: "Acrylic Liquid Emma Nails — material de înaltă performanță cu formulă avansată. Consistența lichidului permite o îmbibare uniformă a pudrei, evitând formarea bulelor de aer. Finit de precizie, se pilește cu ușurință. Nuanța Ivory Silk — alb crem delicat ca mătasea.", price: 9500, category: "acrylic-liquid", subcategory: "acrylic-liquid", size: "30g", inStock: true, featured: false, colorHex: "#F0E2D4", imageUrl: "/acrylic-ivory-silk.jpg", images: ["/acrylic-ivory-silk.jpg"] },
  { slug: "acrylic-liquid-blush-nude", name: "Acrylic Extension Liquid — Blush Nude, 30g", description: "Acrylic Liquid Emma Nails — material de înaltă performanță. Formula avansată oferă modelare fluidă și control absolut. Structură de densitate înaltă — manichiură robustă, ideală și pentru formele lungi. Nuanța Blush Nude — nude roz, camuflaj impecabil.", price: 9500, category: "acrylic-liquid", subcategory: "acrylic-liquid", size: "30g", inStock: true, featured: false, colorHex: "#E0BAA8", imageUrl: "/acrylic-blush-nude.jpg", images: ["/acrylic-blush-nude.jpg"] },
  { slug: "acrylic-liquid-amme-touch", name: "Acrylic Extension Liquid — Amme Touch, 30g", description: "Acrylic Liquid Emma Nails — material de înaltă performanță. Inginerie tehnică pentru manichiuri sculptate cu măiestrie. Eficiență maximă și stabilitate cromatică garantată. Nuanța Amme Touch — nude ambrat cald.", price: 9500, category: "acrylic-liquid", subcategory: "acrylic-liquid", size: "30g", inStock: true, featured: false, colorHex: "#D8B498", imageUrl: "/acrylic-amme-touch.jpg", images: ["/acrylic-amme-touch.jpg"] },

  // ─── BAZE RUBBER ──────────────────────────────────
  { slug: "rubber-base-coat-12ml", name: "Rubber Base Coat, 12ml", description: "Rubber Base Emma Nails — fundamentul esențial pentru o manichiură tehnică de succes. Concepută special pentru unghiile subțiri, casante sau problematice, oferă aderență magnetică și flexibilitate rezistentă. Vâscozitate inteligentă, tehnologie \"Shock-Absorb\" ce absoarbe șocurile mecanice, autonivelare high-definition și camuflaj sofisticat. Economie de timp — înlocuiește aplicarea culorii, reducând durata procedurii cu până la 20 de minute. Garantează manichiură intactă peste 4 săptămâni.", price: 6500, category: "baze-rubber", subcategory: "rubber-base", size: "12ml", inStock: true, featured: false, imageUrl: "/rubber-base-coat-front.jpg", images: ["/rubber-base-coat-front.jpg", "/rubber-base-coat-back.jpg"] },
  { slug: "glitter-rubber-base-coat-12ml", name: "Glitter Rubber Base Coat, 12ml", description: "Glitter Rubber Base Emma Nails — soluția 2-în-1 care combină rezistența unei baze elastice cu estetica prețioasă a sclipiciului fin. Efect \"Jewel-Tone\" cu particule de sclipici de înaltă densitate, suspendate într-o formulă autonivelantă. Aderență magnetică pe unghiile subțiri, camuflaj și design din aplicare unică. Economie de timp — înlocuiește aplicarea culorii. Rezistență 4 săptămâni — menține strălucirea particulelor fără a se mătui.", price: 7000, category: "baze-rubber", subcategory: "glitter-rubber-base", size: "12ml", inStock: true, featured: false, imageUrl: "/glitter-rubber-base-front.jpg", images: ["/glitter-rubber-base-front.jpg", "/glitter-rubber-base-back.jpg"] },

  // ─── GEL CONSTRUCȚIE — Liquids ─────────────────────
  { slug: "self-leveling-fit-gel-12ml", name: "Self-leveling Fit Gel, 12ml", description: "Builder Liquid Emma Nails — gel de construcție \"la sticluță\" ce redefinește eficiența în salon. Textură inovatoare care se autonivelează instantaneu, formează o legătură moleculară puternică și minimizează degajarea de căldură la polimerizare. Aplicare directă cu pensula din sticlă, necesită pilire minimă sau deloc. Perfect pentru protecția unghiilor naturale medii sau lungi.", price: 7000, category: "gel-constructie", subcategory: "gel-liquid", size: "12ml", inStock: true, featured: false, imageUrl: "/self-leveling-fit-gel-front.jpg", images: ["/self-leveling-fit-gel-front.jpg", "/self-leveling-fit-gel-back.jpg"] },
  { slug: "balance-builder-liquid-12ml", name: "Balance Builder Liquid, 12ml", description: "Builder Liquid Emma Nails — inovația care redefinește eficiența în salon. Densitatea necesară pentru întărirea unghiei naturale și fluiditatea ideală pentru tehnica fără pilire. Formula optimizată minimizează degajarea de căldură, fiind ideală pentru unghii sensibile. Aplicare directă cu pensula din sticlă. Controlul unui gel, simplitatea unei baze.", price: 7000, category: "gel-constructie", subcategory: "gel-liquid", size: "12ml", inStock: true, featured: false, imageUrl: "/balance-builder-liquid-front.jpg", images: ["/balance-builder-liquid-front.jpg", "/balance-builder-liquid-back.jpg"] },

  // ─── GEL CONSTRUCȚIE — Builder Gel ──────────────────
  { slug: "builder-gel-white-wonder", name: "Builder Gel — White Wonder, 30g", description: "Harmony Builder Gel (HEMA – TPO FREE). Structură rigidă cu polimerizare la rece, confort maxim și durabilitate peste 4 săptămâni. Proprietăți excelente de autonivelare — reduce timpul de finisare cu 30%. Culori stabile, fără îngălbenire. Nuanța White Wonder — alb pur luminos.", price: 9500, category: "gel-constructie", subcategory: "builder-gel", size: "30g", inStock: true, featured: false, colorHex: "#F5F0EB", imageUrl: "/builder-gel-white-wonder.jpg", images: ["/builder-gel-white-wonder.jpg"] },
  { slug: "builder-gel-still-white", name: "Builder Gel — Still White, 30g", description: "Mood Cover Builder Gel (HEMA – TPO FREE). Structură rigidă, polimerizare la rece. Vâscozitate optimizată care nu curge, ideal pentru extensii lungi și forme extreme cu precizie milimetrică. Nuanța Still White — alb cremos, camuflaj impecabil.", price: 9500, category: "gel-constructie", subcategory: "builder-gel", size: "30g", inStock: true, featured: false, colorHex: "#F2EDE8", imageUrl: "/builder-gel-still-white.jpg", images: ["/builder-gel-still-white.jpg"] },
  { slug: "builder-gel-soul-sisters", name: "Builder Gel — Soul Sisters, 30g", description: "Glow Moment Builder Gel (ODORLESS, HEMA – TPO FREE). Structură moleculară densă ce previne ruperea sau crăparea. Permite modelarea prelungită fără migrare spre cuticulă. Nuanța Soul Sisters — shimmer iridescent delicat.", price: 9500, category: "gel-constructie", subcategory: "builder-gel", size: "30g", inStock: true, featured: false, colorHex: "#E5DCE8", imageUrl: "/builder-gel-soul-sisters.jpg", images: ["/builder-gel-soul-sisters.jpg"] },
  { slug: "builder-gel-pink-promise", name: "Builder Gel — Pink Promise, 30g", description: "Fairy Kiss Builder Gel (HEMA – TPO FREE). Autonivelare excelentă, reduce timpul de finisare cu 30%. Culori stabile fără îngălbenire, aspect natural sau camuflaj perfect. Nuanța Pink Promise — roz promisiune, feminin și delicat.", price: 9500, category: "gel-constructie", subcategory: "builder-gel", size: "30g", inStock: true, featured: false, colorHex: "#F0A8BC", imageUrl: "/builder-gel-pink-promise.jpg", images: ["/builder-gel-pink-promise.jpg"] },
  { slug: "builder-gel-pink-filter", name: "Builder Gel — Pink Filter, 30g", description: "Pearl Soft Mode Builder Gel (TPO FREE). Proprietăți excelente de autonivelare. Modelarea prelungită fără migrare spre cuticulă — ideal pentru începători și profesioniști. Nuanța Pink Filter — roz filtrat, efect \"glass skin\" pe unghie.", price: 9500, category: "gel-constructie", subcategory: "builder-gel", size: "30g", inStock: true, featured: false, colorHex: "#ECA8B8", imageUrl: "/builder-gel-pink-filter.jpg", images: ["/builder-gel-pink-filter.jpg"] },
  { slug: "builder-gel-pearl-touch", name: "Builder Gel — Pearl Touch, 30g", description: "Fairy Kiss Builder Gel (HEMA – TPO FREE). Structură rigidă, confort maxim la purtare. Polimerizare la rece — minimizează disconfortul. Nuanța Pearl Touch — perlat delicat cu reflexe calde.", price: 9500, category: "gel-constructie", subcategory: "builder-gel", size: "30g", inStock: true, featured: false, colorHex: "#EDE4DA", imageUrl: "/builder-gel-pearl-touch.jpg", images: ["/builder-gel-pearl-touch.jpg"] },
  { slug: "builder-gel-nude-soft", name: "Builder Gel — Nude Soft, 30g", description: "Harmony Builder Gel (HEMA – TPO FREE). Durabilitate peste 4 săptămâni, vâscozitate optimizată care nu curge. Culori stabile fără îngălbenire. Nuanța Nude Soft — nude clasic, camuflaj natural.", price: 9500, category: "gel-constructie", subcategory: "builder-gel", size: "30g", inStock: true, featured: false, colorHex: "#D8C0AD", imageUrl: "/builder-gel-nude-soft.jpg", images: ["/builder-gel-nude-soft.jpg"] },
  { slug: "builder-gel-my-alma", name: "Builder Gel — My Alma, 30g", description: "Pearl Soft Mode Builder Gel (TPO FREE). Autonivelare superbă, reduce finisarea cu 30%. Ideal atât pentru tehnicieni rapizi cât și pentru începători. Nuanța My Alma — nude cald cu suflet perlat.", price: 9500, category: "gel-constructie", subcategory: "builder-gel", size: "30g", inStock: true, featured: false, colorHex: "#D4AE98", imageUrl: "/builder-gel-my-alma.jpg", images: ["/builder-gel-my-alma.jpg"] },
  { slug: "builder-gel-moon-shimmer", name: "Builder Gel — Moon Shimmer, 30g", description: "Glow Moment Builder Gel (ODORLESS, HEMA – TPO FREE). Structură moleculară densă, previne ruperea și pierderea curbei C. Modelare prelungită fără migrare. Nuanța Moon Shimmer — shimmer selenar cu reflexe subtile.", price: 9500, category: "gel-constructie", subcategory: "builder-gel", size: "30g", inStock: true, featured: false, colorHex: "#E0D8E4", imageUrl: "/builder-gel-moon-shimmer.jpg", images: ["/builder-gel-moon-shimmer.jpg"] },
  { slug: "builder-gel-metal-bloom", name: "Builder Gel — Metal Bloom, 30g", description: "Diamond Boss Builder Gel (HEMA – TOP FREE). Structură rigidă de elită, polimerizare la rece. Vâscozitate optimizată pentru extensii lungi și forme extreme. Nuanța Metal Bloom — metalic cu inflorescentă roz-argintie.", price: 9500, category: "gel-constructie", subcategory: "builder-gel", size: "30g", inStock: true, featured: false, colorHex: "#C0B8C4", imageUrl: "/builder-gel-metal-bloom.jpg", images: ["/builder-gel-metal-bloom.jpg"] },
  { slug: "builder-gel-lilac-anne", name: "Builder Gel — Lilac Anne, 30g", description: "Fairy Kiss Builder Gel (HEMA – TPO FREE). Autonivelare excelentă, culori stabile fără îngălbenire. Aspect natural sau camuflaj perfect. Nuanța Lilac Anne — liliac romantic cu profunzime.", price: 9500, category: "gel-constructie", subcategory: "builder-gel", size: "30g", inStock: true, featured: false, colorHex: "#C8A8C8", imageUrl: "/builder-gel-lilac-anne.jpg", images: ["/builder-gel-lilac-anne.jpg"] },
  { slug: "builder-gel-lara-glow", name: "Builder Gel — Lara Glow, 30g", description: "Pearl Soft Mode Builder Gel (TPO FREE). Proprietăți excelente de autonivelare, modelarea prelungită fără migrare. Nuanța Lara Glow — nude cald cu strălucire subtilă.", price: 9500, category: "gel-constructie", subcategory: "builder-gel", size: "30g", inStock: true, featured: false, colorHex: "#D8BCAA", imageUrl: "/builder-gel-lara-glow.jpg", images: ["/builder-gel-lara-glow.jpg"] },
  { slug: "builder-gel-cosmic-chrome", name: "Builder Gel — Cosmic Chrome, 30g", description: "Diamond Boss Builder Gel (HEMA – TOP FREE). Structură rigidă de elită cu polimerizare la rece. Confort maxim la purtare și durabilitate peste 4 săptămâni. Nuanța Cosmic Chrome — efect cromat cosmic cu reflexe multidimensionale.", price: 9500, category: "gel-constructie", subcategory: "builder-gel", size: "30g", inStock: true, featured: false, colorHex: "#B8B8C8", imageUrl: "/builder-gel-cosmic-chrome.jpg", images: ["/builder-gel-cosmic-chrome.jpg"] },
  { slug: "builder-gel-blue-chill", name: "Builder Gel — Blue Chill, 30g", description: "Pearl Soft Mode Builder Gel (TPO FREE). Autonivelare superbă, reduce finisarea cu 30%. Versatilitate HEMA-Free pentru unghii sensibile. Nuanța Blue Chill — albastru rece cu personalitate.", price: 9500, category: "gel-constructie", subcategory: "builder-gel", size: "30g", inStock: true, featured: false, colorHex: "#A4BCD6", imageUrl: "/builder-gel-blue-chill.jpg", images: ["/builder-gel-blue-chill.jpg"] },
  { slug: "builder-gel-beige-cuddle", name: "Builder Gel — Beige Cuddle, 30g", description: "Pearl Soft Mode Builder Gel (TPO FREE). Proprietăți excelente de autonivelare. Culori stabile fără îngălbenire. Nuanța Beige Cuddle — bej cald, îmbrățișare de culoare.", price: 9500, category: "gel-constructie", subcategory: "builder-gel", size: "30g", inStock: true, featured: false, colorHex: "#D8C4A8", imageUrl: "/builder-gel-beige-cuddle.jpg", images: ["/builder-gel-beige-cuddle.jpg"] },
  { slug: "builder-gel-alle-vibes", name: "Builder Gel — Allè Vibes, 30g", description: "Diamond Boss Builder Gel (HEMA – TOP FREE). Structură moleculară densă, previne ruperea, crăparea sau pierderea formei pe toată durata purtării. Nuanța Allè Vibes — vibrații metalice sofisticate.", price: 9500, category: "gel-constructie", subcategory: "builder-gel", size: "30g", inStock: true, featured: false, colorHex: "#C4B4CC", imageUrl: "/builder-gel-alle-vibes.jpg", images: ["/builder-gel-alle-vibes.jpg"] },

  // ─── GEL CONSTRUCȚIE — Jelly ──────────────────────
  { slug: "jelly-gel-nude-in-control", name: "Jelly Builder Gel — Nude In Control, 30g", description: "Tender Crush Jelly Builder Gel (HEMA – TPO FREE). Consistență densă de tip jeleu — materialul rămâne exact unde este plasat, fără a migra spre cuticule. Odorless & HEMA-Free, reduce riscul de alergii. Barieră extrem de dură care nu se fisurează. Nuanța Nude In Control — nude controlat cu căldură.", price: 9500, category: "gel-constructie", subcategory: "jelly", size: "30g", inStock: true, featured: false, colorHex: "#D8A0AC", imageUrl: "/jelly-gel-nude-in-control.jpg", images: ["/jelly-gel-nude-in-control.jpg"] },
  { slug: "jelly-gel-nude-delight", name: "Jelly Builder Gel — Nude Delight, 30g", description: "Tender Crush Jelly Builder Gel (HEMA – TPO FREE). Control total — gelul nu se prelinge în șanțurile periunghiale. Camuflaj perfect între unghia naturală și extensie. Nuanța Nude Delight — bucuria nude-ului luminos.", price: 9500, category: "gel-constructie", subcategory: "jelly", size: "30g", inStock: true, featured: false, colorHex: "#E0C4B2", imageUrl: "/jelly-gel-nude-delight.jpg", images: ["/jelly-gel-nude-delight.jpg"] },
  { slug: "jelly-gel-liliac-sand", name: "Jelly Builder Gel — Liliac Sand, 30g", description: "Tender Crush Jelly Builder Gel (HEMA – TPO FREE). Consistență densă de tip jeleu, Odorless & HEMA-Free. Precizie milimetrică la construcție, barieră dură fără fisuri. Nuanța Liliac Sand — nisip liliac cu reflexe misterioase.", price: 9500, category: "gel-constructie", subcategory: "jelly", size: "30g", inStock: true, featured: false, colorHex: "#C4A4B8", imageUrl: "/jelly-gel-liliac-sand.jpg", images: ["/jelly-gel-liliac-sand.jpg"] },
  { slug: "jelly-gel-jelly-rose", name: "Jelly Builder Gel — Jelly Rose, 30g", description: "Tender Crush Jelly Builder Gel (HEMA – TPO FREE). Materialul rămâne exact unde e plasat. Odorless, confort sporit la polimerizare. Camuflaj natural și elegant. Nuanța Jelly Rose — trandafir în jeleu.", price: 9500, category: "gel-constructie", subcategory: "jelly", size: "30g", inStock: true, featured: false, colorHex: "#E8A0AB", imageUrl: "/jelly-gel-jelly-rose.jpg", images: ["/jelly-gel-jelly-rose.jpg"] },
  { slug: "jelly-gel-jelly-milk", name: "Jelly Builder Gel — Jelly Milk, 30g", description: "Tender Crush Jelly Builder Gel (HEMA – TPO FREE). Control total al plasării, nu migrează spre cuticule. Barieră extrem de dură după polimerizare. Nuanța Jelly Milk — alb lăptos, baza perfectă.", price: 9500, category: "gel-constructie", subcategory: "jelly", size: "30g", inStock: true, featured: false, colorHex: "#F0E8DF", imageUrl: "/jelly-gel-jelly-milk.jpg", images: ["/jelly-gel-jelly-milk.jpg"] },

  // ─── TOP COAT ──────────────────────────────────────
  { slug: "glitter-vibe-top-coat-12ml", name: "Glitter Vibe Top Coat, 12ml", description: "Glitter Vibe Top Coat Emma Nails — finisajul suprem \"No Wipe\" infuzat cu micro-particule strălucitoare într-o formulă ultra-lucioasă. Tehnologie No-Wipe cu luciu instantaneu de oglindă, densitate omogenă a sclipiciului, barieră anti-zgârieturi și filtru de protecție cromatică. Se aplică peste baze rubber, geluri de construcție sau oje semipermanente. Adaugă efect de \"praf de stele\" oricărei nuanțe.", price: 7000, category: "top-coat", subcategory: "glitter-vibe-top", size: "12ml", inStock: true, featured: false, imageUrl: "/glitter-vibe-top-coat-front.jpg", images: ["/glitter-vibe-top-coat-front.jpg", "/glitter-vibe-top-coat-back.jpg"] },
  { slug: "clear-steel-top-coat-12ml", name: "Clear Steel Top Coat, 12ml", description: "Top Clear Steel Emma Nails — finisajul de elită \"No Wipe\" conceput pentru protecție îndelungată. Formulă inspirată de rezistența oțelului, cu scut protector ultra-rigid și luciu vitros impecabil. Imun la micro-zgârieturi, claritate superioară pe 4 săptămâni. Protejează împotriva decolorării și îngălbenirii. Aplicare ultra-subțire care se autonivelează perfect.", price: 7000, category: "top-coat", subcategory: "clear-steel-top", size: "12ml", inStock: true, featured: false, imageUrl: "/clear-steel-top-coat-front.jpg", images: ["/clear-steel-top-coat-front.jpg", "/clear-steel-top-coat-back.jpg"] },
  { slug: "velvet-matte-top-coat-12ml", name: "Velvet Matte Top Coat, 12ml", description: "Top Velvet Matte Emma Nails — finisaj \"No Wipe\" cu efect mat absolut. Transformă orice manichiură într-o experiență vizuală și tactilă de lux. Textură fină asemănătoare catifelei, senzație catifelată la atingere, respinge praful și transferul de culoare. Aplicare uniformă fără dâre, nu modifică arhitectura apexului. Ideal pentru tehnici mixte (mat vs. lucios) și French modern.", price: 7000, category: "top-coat", subcategory: "velvet-matte-top", size: "12ml", inStock: true, featured: false, imageUrl: "/velvet-matte-top-coat-front.jpg", images: ["/velvet-matte-top-coat-front.jpg", "/velvet-matte-top-coat-back.jpg"] },
];

export const courses = [
  { slug: "curs-baza-stilist-protezist-unghii-nivel-1", name: "Curs bază stilist protezist unghii — Nivel 1", description: "Cursul ideal pentru începătoare. 5 zile intensive de teorie + practică pe model real.", priceFrom: 40000, priceTo: 270000, level: "incepator", duration: "5 zile", curriculum: ["Ziua 1: Teorie — Anatomia unghiei, patologie, norme de igienă","Ziua 1: Aplicarea ojei semipermanente în tehnica fără pilire","Ziua 2: Oval slim cu tipsuri full (fără apex) — design pietre","Ziua 3: Pătrat cu full tips & design pietre","Ziua 4: Migdală clasică pe șablon — Babyboomer","Ziua 5: French de suprafață & realizare portofoliu foto"], includes: ["Diplomă acreditată","Practică pe model real","Suport de curs","Consultanță post-curs"], dates: ["19-23 Ianuarie","9-13 Februarie","9-13 Martie","27 Aprilie-01 Mai","25-29 Mai","22-26 Iunie","20-24 Iulie","24-27 August"], hasAccreditation: true, featured: true, imageUrl: "https://academy.emmanails.ro/wp-content/uploads/2024/05/WhatsApp-Image-2025-11-04-at-21.36.26.jpeg", images: ["https://academy.emmanails.ro/wp-content/uploads/2024/04/WhatsApp-Image-2025-06-09-at-11.19.42-1.webp","https://academy.emmanails.ro/wp-content/uploads/2024/04/WhatsApp-Image-2025-08-23-at-13.21.50.jpeg","https://academy.emmanails.ro/wp-content/uploads/2024/05/WhatsApp-Image-2025-11-04-at-21.36.26.jpeg","https://academy.emmanails.ro/wp-content/uploads/2024/05/WhatsApp-Image-2025-11-04-at-21.59.52-1-1.jpeg"] },
  { slug: "curs-perfectionare-gel-nivel-1", name: "Curs perfecționare gel — Nivel 1", description: "Perfecționare pentru cele care au terminat cursul de bază.", priceFrom: 25000, priceTo: 180000, level: "mediu", duration: "2-3 zile", curriculum: ["Ziua 1: Oval slim cu tipsuri full (fără apex)","Ziua 2: Pătrat natural cu tipsuri smart","Ziua 3: Migdală clasică pe șablon — Babyboomer"], includes: ["Diplomă","Practică pe model real"], dates: ["20-21 Ianuarie","10-12 Februarie","10-12 Martie","28-30 Aprilie","26-28 Mai","23-25 Iunie","21-23 Iulie","25-26 August"], hasAccreditation: false, featured: true, imageUrl: "https://academy.emmanails.ro/wp-content/uploads/2024/04/WhatsApp-Image-2024-04-16-at-10.32.35-1.jpeg", images: ["https://academy.emmanails.ro/wp-content/uploads/2024/04/WhatsApp-Image-2024-04-16-at-10.32.35-1.jpeg","https://academy.emmanails.ro/wp-content/uploads/2024/05/WhatsApp-Image-2024-06-07-at-16.27.57.jpeg","https://academy.emmanails.ro/wp-content/uploads/2024/05/WhatsApp-Image-2025-09-21-at-08.46.02-2.jpeg"] },
  { slug: "curs-oja-semipermanenta", name: "Curs aplicare ojă semipermanentă", description: "Tehnica completă de aplicare a ojei semipermanente.", priceFrom: 10000, priceTo: 60000, level: "incepator", duration: "1 zi", curriculum: ["Ziua 1: Tehnica completă de aplicare ojă semipermanentă"], includes: ["Diplomă","Practică pe model real"], dates: ["19 Ianuarie","9 Februarie","9 Martie","27 Aprilie","25 Mai","22 Iunie","20 Iulie","24 August"], hasAccreditation: false, featured: true, imageUrl: "https://academy.emmanails.ro/wp-content/uploads/2024/05/WhatsApp-Image-2024-04-16-at-11.33.22.jpeg", images: ["https://academy.emmanails.ro/wp-content/uploads/2024/05/WhatsApp-Image-2024-04-16-at-11.33.22.jpeg","https://academy.emmanails.ro/wp-content/uploads/2024/05/WhatsApp-Image-2025-06-09-at-12.02.48.webp"] },
  { slug: "curs-intretinere-simpla", name: "Curs întreținere simplă", description: "Curs de o zi — tehnica de întreținere simplă.", priceFrom: 10000, priceTo: 80000, level: "incepator", duration: "1 zi", curriculum: ["Ziua 1: Tehnica completă de întreținere simplă a unghiilor construite"], includes: ["Diplomă","Practică pe model real"], dates: ["23 Ianuarie","13 Februarie","13 Martie","1 Mai","29 Mai","26 Iunie","24 Iulie","27 August"], hasAccreditation: false, featured: true, imageUrl: "https://academy.emmanails.ro/wp-content/uploads/2024/04/3abd0d45-45a2-46dc-9988-e4345e03d24f.jpg", images: ["https://academy.emmanails.ro/wp-content/uploads/2024/04/3abd0d45-45a2-46dc-9988-e4345e03d24f.jpg","https://academy.emmanails.ro/wp-content/uploads/2024/04/4cb4f10b-54c7-4771-b2a9-25278a94234a.jpg"] },
  { slug: "curs-baza-stilist-protezist-unghii-nivel-2", name: "Curs bază stilist protezist unghii — Nivel 2", description: "Continuarea cursului de bază. Tehnici avansate de construcție, french exterior și interior.", priceFrom: 40000, priceTo: 250000, level: "mediu", duration: "5 zile", curriculum: ["Ziua 1: Migdală modernă cu double side pe șablon","Ziua 2: Pătrat arcuit cu french de suprafață","Ziua 3: Migdală modernă cu french pictat pe șablon","Ziua 4: Balerină cu french de interior pe șablon","Ziua 5: Întreținere cu schimbarea arhitecturii cu tipsuri reutilizabile"], includes: ["Diplomă acreditată","Practică pe model real"], dates: ["16-20 Februarie","30 Martie-3 Aprilie","4-8 Mai","1-5 Iunie","29 Iunie-3 Iulie","27-31 Iulie","31 August-4 Septembrie"], hasAccreditation: true, featured: false, imageUrl: "https://academy.emmanails.ro/wp-content/uploads/2024/05/WhatsApp-Image-2024-04-16-at-11.35.36.jpeg", images: ["https://academy.emmanails.ro/wp-content/uploads/2024/05/WhatsApp-Image-2024-04-16-at-11.35.36.jpeg","https://academy.emmanails.ro/wp-content/uploads/2024/05/WhatsApp-Image-2025-11-04-at-21.00.36-1.jpeg","https://academy.emmanails.ro/wp-content/uploads/2024/05/WhatsApp-Image-2025-11-04-at-21.16.36.jpeg"] },
  { slug: "curs-perfectionare-gel-nivel-2", name: "Curs perfecționare gel — Nivel 2", description: "Perfecționare avansată în tehnicile de gel.", priceFrom: 30000, priceTo: 200000, level: "avansat", duration: "3 zile", curriculum: ["Ziua 1: Oval slim cu tipsuri reutilizabile","Ziua 2: Pătrat arcuit cu french de interior cu tipsuri reutilizabile","Ziua 3: Migdală modernă cu french de interior cu tipsuri reutilizabile"], includes: ["Diplomă","Practică pe model real"], dates: ["16-18 Februarie","30 Martie-3 Aprilie","4-6 Mai","1-3 Iunie","29 Iunie-1 Iulie","27-29 Iulie","31 August-3 Septembrie"], hasAccreditation: false, featured: false, imageUrl: "https://academy.emmanails.ro/wp-content/uploads/2024/05/WhatsApp-Image-2025-11-04-at-21.05.20.jpeg", images: ["https://academy.emmanails.ro/wp-content/uploads/2024/05/WhatsApp-Image-2025-11-04-at-21.05.20.jpeg","https://academy.emmanails.ro/wp-content/uploads/2024/05/WhatsApp-Image-2025-11-04-at-21.12.35.jpeg"] },
  { slug: "curs-intretinere-schimbarea-arhitecturii", name: "Curs întreținere cu schimbarea arhitecturii", description: "1 zi, 8-10 ore. Tehnica completă de întreținere cu schimbarea formei.", priceFrom: 15000, priceTo: 100000, level: "mediu", duration: "1 zi", curriculum: ["Ziua 1: Tehnica completă de întreținere cu schimbarea formei unghiei — 8-10 ore"], includes: ["Diplomă","Practică pe model real"], dates: ["20 Februarie","3 Martie","8 Mai","5 Iunie","3 Iulie","31 Iulie","4 Septembrie"], hasAccreditation: false, featured: false, imageUrl: "https://academy.emmanails.ro/wp-content/uploads/2024/05/WhatsApp-Image-2024-07-10-at-13.46.40-1.jpeg", images: ["https://academy.emmanails.ro/wp-content/uploads/2024/05/WhatsApp-Image-2024-07-10-at-13.46.40-1.jpeg","https://academy.emmanails.ro/wp-content/uploads/2024/05/WhatsApp-Image-2024-06-07-at-16.22.35.jpeg"] },
  { slug: "curs-perfectionare-gel-nivel-3", name: "Curs perfecționare gel — Nivel 3", description: "Cel mai avansat nivel. Tehnici de top, forme extreme.", priceFrom: 35000, priceTo: 250000, level: "avansat", duration: "3 zile", curriculum: ["Ziua 1: Migdală gotică pe șablon cu french de interior","Ziua 2: Edge clasic cu french de interior"], includes: ["Diplomă","Practică pe model real"], dates: ["11-13 Mai","17-19 Iunie","15-17 Iulie"], hasAccreditation: false, featured: false, imageUrl: "https://academy.emmanails.ro/wp-content/uploads/2024/04/e2138287-df35-4c04-98e6-95ed273f9d78.jpg", images: ["https://academy.emmanails.ro/wp-content/uploads/2024/04/e2138287-df35-4c04-98e6-95ed273f9d78.jpg","https://academy.emmanails.ro/wp-content/uploads/2024/05/WhatsApp-Image-2024-04-25-at-22.06.31-2.jpeg","https://academy.emmanails.ro/wp-content/uploads/2024/05/WhatsApp-Image-2025-06-09-at-12.20.48.webp"] },
  { slug: "curs-fast-tips-manicure", name: "Curs Fast Tips Manicure", description: "Tehnica fast tips — French Glass, pilirea și finisarea.", priceFrom: 20000, priceTo: 120000, level: "mediu", duration: "2 zile", curriculum: ["Ziua 1: Pătrat cu full tips & design pietre","Ziua 2: Natural slim cu smart tips","Ziua 3: Migdală clasică/slim pe șablon"], includes: ["Diplomă","Practică pe model real"], dates: ["15-16 Aprilie","7-8 Mai","4-5 Iunie","2-3 Iulie","30-31 Iulie","3-4 Septembrie"], hasAccreditation: false, featured: false, imageUrl: "https://academy.emmanails.ro/wp-content/uploads/2024/05/WhatsApp-Image-2025-06-09-at-10.41.15-1.webp", images: ["https://academy.emmanails.ro/wp-content/uploads/2024/05/WhatsApp-Image-2025-06-09-at-10.41.15-1.webp","https://academy.emmanails.ro/wp-content/uploads/2024/12/WhatsApp-Image-2025-06-03-at-11.51.08-7.jpeg"] },
  { slug: "curs-smart-pedicure", name: "Curs Smart Pedicure — Pedichiură Estetică", description: "Pedichiură estetică modernă.", priceFrom: 25000, priceTo: 160000, level: "mediu", duration: "2 zile", curriculum: ["Ziua 1: Pedichiură estetică — tehnici moderne","Ziua 2: Practică pe model — finisare completă"], includes: ["Diplomă","Practică pe model"], dates: ["2-3 Februarie","23-24 Aprilie","14-15 Mai","8-9 Iunie","13-14 Iulie","3-4 August"], hasAccreditation: true, featured: false, imageUrl: "https://academy.emmanails.ro/wp-content/uploads/2024/05/WhatsApp-Image-2024-04-25-at-22.00.14.jpeg", images: ["https://academy.emmanails.ro/wp-content/uploads/2024/05/WhatsApp-Image-2024-04-25-at-22.00.13.jpeg","https://academy.emmanails.ro/wp-content/uploads/2024/05/WhatsApp-Image-2024-04-25-at-22.00.14.jpeg","https://academy.emmanails.ro/wp-content/uploads/2024/05/WhatsApp-Image-2024-07-10-at-14.20.53-1.jpeg"] },
  { slug: "curs-pedichiura-complexa", name: "Curs pedichiură complexă", description: "Cel mai complet curs de pedichiură. Unghii încarnate, micoze, bătături, reconstrucție.", priceFrom: 40000, priceTo: 280000, level: "avansat", duration: "3 zile", curriculum: ["Ziua 1: Tehnici de bază pedichiură complexă","Ziua 2: Unghii încarnate, sisteme de corecție","Ziua 3: Micoze, bătături, reconstrucție"], includes: ["Diplomă acreditată","Practică cu 2 modele pe zi"], dates: ["26-28 Ianuarie","23-25 Februarie","20-22 Aprilie","18-20 Mai","10-12 Iunie","6-8 Iulie","17-19 August"], hasAccreditation: true, featured: false, imageUrl: "https://academy.emmanails.ro/wp-content/uploads/2024/04/957ceb81-2e15-46a9-b978-a7ac26d8cc51.jpg", images: ["https://academy.emmanails.ro/wp-content/uploads/2024/04/957ceb81-2e15-46a9-b978-a7ac26d8cc51.jpg","https://academy.emmanails.ro/wp-content/uploads/2024/05/WhatsApp-Image-2024-07-10-at-15.22.46.jpeg","https://academy.emmanails.ro/wp-content/uploads/2024/05/WhatsApp-Image-2024-07-10-at-15.22.48-1.jpeg","https://academy.emmanails.ro/wp-content/uploads/2024/05/WhatsApp-Image-2024-11-28-at-14.04.02.jpeg"] },
  { slug: "curs-sisteme-corectie", name: "Curs sisteme de corecție", description: "Sisteme moderne de corecție a unghiilor încarnate.", priceFrom: 30000, priceTo: 180000, level: "avansat", duration: "2 zile", curriculum: ["Ziua 1: Sisteme de corecție — teorie și aplicare bracketuri","Ziua 2: Practică pe model — tehnici non-invazive"], includes: ["Diplomă","Practică pe model real"], dates: ["29-30 Ianuarie","26-27 Februarie","21-22 Mai","15-16 Iunie","9-10 Iulie","20-21 August"], hasAccreditation: false, featured: false, imageUrl: "https://academy.emmanails.ro/wp-content/uploads/2024/05/WhatsApp-Image-2024-07-10-at-15.19.54-1.jpeg", images: ["https://academy.emmanails.ro/wp-content/uploads/2024/05/WhatsApp-Image-2024-07-10-at-15.19.54-1.jpeg","https://academy.emmanails.ro/wp-content/uploads/2024/05/WhatsApp-Image-2025-06-09-at-13.12.17-1.webp"] },
];
